BLEN-264: Basic integration MaterialX nodes into Blender shader nodetree
bnagirniak/blender-addons pull request #14
Opened 2022-11-23 14:54 UTC by DagerD

Partially removed MaterialX node tree and corresponded code.
All MaterialX nodes moved to Blender shader node tree.
MaterialX nodes and Blender nodes now work between each other.

it is possible to have MaterialX `surfacematerial` node or Blender `Material Output` node for material (both works).

Moved functions `import, export, print to console` to Blender shader node tree.

MaterialX library works.
Viewport render works (but not final).

I suggest to do some refactoring and improvements and getting rid of redundant code in separate tasks since here is a lot of testing work already.

2022-11-28 12:58 UTC, bnagirniak requested changes
Combine material/ui.py and nodes.ui.py -> ui.py.
Remove unused code.

2022-11-28 12:58 UTC, bnagirniak commented on materialx/bl_nodes/output.py
> +import MaterialX
import MaterialX as mx

2022-11-28 12:58 UTC, bnagirniak commented on materialx/bl_nodes/shader.py
> +import MaterialX
import MaterialX as mx

2022-11-28 12:58 UTC, bnagirniak commented on materialx/nodes/node.py
> +        return tree.bl_idname == bpy.types.ShaderNodeTree.__name__
change to 'ShaderNodeTree'

2022-11-30 14:45 UTC, DagerD commented
There is an issue with draw node in properties area (see picture): the responsible code of drawing it is placed in cycles, eevee, etc modules (look for `panel_node_draw` method), so we are not able to do anything with it on plugin side.
![image](https://user-images.githubusercontent.com/42409851/204826025-b82eb0ee-aa6f-4790-94a0-0957fb4ea1a0.png)

2022-12-01 09:09 UTC, bnagirniak reviewed
small fixes

2022-12-01 09:09 UTC, bnagirniak commented on materialx/material/__init__.py
> +    ui
from . import ui

2022-12-01 09:09 UTC, bnagirniak commented on materialx/utils.py
> +                 node.bl_idname == ShaderNodeOutputMaterial.__name__ and
use 'ShaderNodeOutputMaterial' instead ShaderNodeOutputMaterial.__name__

2022-12-01 12:21 UTC, bnagirniak approved these changes

2022-12-01 13:33 UTC, merged